### ISSUE TITLE
Default download not working and file not found.

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Paccmann_MCA#1]
It looks like the download of the default data is not returning any results.

Singularity> train.sh 1 /home/awilke/IMPROVE/Singularity/data/ --epochs 1 | head
--epochs is not a file
CMD = python /usr/local/Paccmann_MCA/train.py --epochs 1
using CUDA_VISIBLE_DEVICES 1
using CANDLE_DATA_DIR /home/awilke/IMPROVE/Singularity/data/
using CANDLE_CONFIG
running command python /usr/local/Paccmann_MCA/train.py --epochs 1
/usr/local/conda_envs/Paccmann_MCA/lib/python3.7/site-packages/candle/file_utils.py:217: RuntimeWarning: Path: /home/awilke/IMPROVE/Singularity/data/Paccmann_MCA/Output/EXP000/RUN000 already exists... overwriting.
  warnings.warn(message, RuntimeWarning)
Importing candle utils for pytorch
model name:  Paccmann_MCA
Params:
{'activation': 'relu',
Traceback (most recent call last):
  File "/usr/local/Paccmann_MCA/train.py", line 164, in <module>
    candle_main()
  File "/usr/local/Paccmann_MCA/train.py", line 161, in candle_main
    run(params)
  File "/usr/local/Paccmann_MCA/train.py", line 152, in run
    scores = main(params)
  File "/usr/local/Paccmann_MCA/paccmannmca_baseline_pytorch.py", line 47, in main
    smiles_language = SMILESLanguage.load(smiles_language_filepath)
  File "/usr/local/conda_envs/Paccmann_MCA/lib/python3.7/site-packages/pytoda/smiles/smiles_language.py", line 96, in load
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/awilke/IMPROVE/Singularity/data//common/Data/smiles_language_chembl_gdsc_ccle.pkl'

**Comment by wilke** [comment]
Any progress?

**Comment by priyanka9991** [comment]
The data download happens in the preprocess script. Did you run preprocess before train.sh?
________________________________

**Comment by wilke** [comment]
no, i did not - @adpartin This is breaking the default behavior. We need to fix this as soon as possible. Either documentation or in code.

**Comment by priyanka9991** [comment]
Please let me know if I should move the data download steps within train.py.
________________________________

**Comment by wilke** [comment]
train.py should download its default data if no other data is present. You can keep the same functionality in the prepocess script as well. Right now we are just testing on train.sh with its defaults and it will fail if no data is downloaded.

**Comment by priyanka9991** [comment]
I just pushed my changes to the default branch after adding the data download functionality to train.
________________________________

**Comment by adpartin** [comment]
Originally, preprocess downloads _raw data_ from ftp and generates _ml data_. If we decide to put automatic download into train.py, then it should download the preprocess-generated _ml data_ from ftp. Alternatively, we can add a conditional _if_ statement in train.py that checks whether _ml data_ exists. If it does not, then it calls preprocess.py which generates _ml data._

**Comment by wilke** [comment]
It seems to work now.
