### ISSUE TITLE
test_paccmann.py tries to load model checkpoint from non-existent directory

### ISSUE THREAD

**Issue by jamieOverbeek** [JDACS4C-IMPROVE/Paccmann_MCA#11]
```
  File "/lambda_stor/homes/joverbeek/improve/Paccmann_MCA/test_paccmann.py", line 147, in main
    checkpoint = torch.load(str(file_path + '/save/ckpts/best/model.h5'))
  File "/homes/joverbeek/miniconda3/envs/paccmann_predictor/lib/python3.7/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/lambda_stor/homes/joverbeek/improve/Paccmann_MCA/save/ckpts/best/model.h5'
```

CANDLE saves data in `candle_data_dir/Paccmann_MCA/Output/EXP###/RUN###/`. I'm not sure how to access this directory name within the candle framework.

**Comment by priyanka9991** [comment]
The directory /Paccmann_MCA/save/ckpts is created when executing 'train_csa.py' for saving checkpoints for the best model. infer_csa.py then uses the saved model checkpoint for testing. I did not encounter this error when I tested it again. Could you test it again after running the training script and let me know if the error still exists? @jamieOverbeek

**Comment by jamieOverbeek** [comment]
Hi Priyanka, I have run the preprocess_csa.sh, train_csa.sh, and infer_csa.sh and the infer script ended with the same `FileNotFoundError`. It looks like the `save` directory has not been created

**Comment by priyanka9991** [comment]
I see the problem now. Something changed within candle checkpointing. The version I was using saved checkpoints within /save directory. Let me try to correct the paths. Thanks for checking again.

**Comment by priyanka9991** [comment]
Fixed this issue. Changed the best checkpoint path in the test_paccmann.py script.
