### ISSUE TITLE
Paccmann_MCA

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/Paccmann_MCA#5]
SOP:

- [x] Create improve branch in model repo
- [x] Switch to improve branch in image build
- [x] Test container build
- [x] Test train with container
- [x] Test HPO
- [x] Tag improve branch with v0.6.0

**Comment by wilke** [comment]
HPO test performed by @priyanka9991

**Comment by priyanka9991** [comment]
RESULTS OF THE HPO TEST:

<img width="730" alt="Screen Shot 2023-09-18 at 4 10 30 PM" src="https://github.com/JDACS4C-IMPROVE/Paccmann_MCA/assets/86702829/dece19a9-4365-4977-9885-2f68a99f6c6a">



<img width="829" alt="Screen Shot 2023-09-18 at 4 11 00 PM" src="https://github.com/JDACS4C-IMPROVE/Paccmann_MCA/assets/86702829/c13a9b36-9b2e-4e79-bb52-d55a25415e1c">
